// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  hero: dynamic(() => import("./Hero")),
  icon_text_highlights: dynamic(() => import("./AboutContent")),
  materials_grid: dynamic(() => import("./Materials")),
  process: dynamic(() => import("./Process")),
  rich_text: dynamic(() => import("./RichText")),
  service_listing_navigation: dynamic(() => import("./Services")),
  works: dynamic(() => import("./Works")),
};
